### ISSUE TITLE
Clarification Regarding the ADHD Dataset Used in This Repository

### ISSUE THREAD

**Issue by furmanlukasz** [sara-gaballa/ADHD-detection-from-EEG-signals-using-ML-and-DL-models#1]
Hello @sara-gaballa 

I am interested in the ADHD dataset utilized in this repository and am seeking some clarification regarding its contents. Specifically, I am curious about the number of subjects included in the dataset. Could you kindly provide details on the count of individuals or subjects that were part of this dataset? 

Thank you very much for your time and assistance.

Best regards,
Lukas

**Comment by sara-gaballa** [comment]
Hello @furmanlukasz,

Thank you for reaching out and expressing interest in the ADHD dataset.

The dataset contains data from a total of 144 children, comprising 44 healthy children and 100 children diagnosed with the disorder.

And then after data segmentation, it is classified as follows:

Control group: N = 10,129 trials
ADD group: N = 13,031 trials
ADHD group: N = 10,742 trials
If you have any more questions or need further clarification, feel free to ask.

Best regards,
Sara Gaballa

**Comment by furmanlukasz** [comment]
Thank you @sara-gaballa. 

Best regards, 
Lukas
